package co.edu.unbosque.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mrfixthis
 */
public class BaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrameView
     */
    public BaseFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        playListCreatorTittleLabel = new javax.swing.JLabel();
        stationOptions = new javax.swing.JComboBox<>();
        playListNameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        soundsList = new javax.swing.JTable();
        acceptButton = new javax.swing.JButton();
        stationSelectorLabel = new javax.swing.JLabel();
        playListNameLabel = new javax.swing.JLabel();
        baseFrameMenuBar = new javax.swing.JMenuBar();
        importSoundOption = new javax.swing.JMenu();
        closeAppOption = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(520, 460));

        jPanel1.setLayout(null);

        playListCreatorTittleLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        playListCreatorTittleLabel.setText("Crear PlayList");
        jPanel1.add(playListCreatorTittleLabel);
        playListCreatorTittleLabel.setBounds(180, 20, 167, 29);

        stationOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stationOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(stationOptions);
        stationOptions.setBounds(280, 90, 180, 30);

        playListNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playListNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(playListNameField);
        playListNameField.setBounds(70, 90, 180, 30);

        soundsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Artista", "Genero"
            }
        ));
        jScrollPane2.setViewportView(soundsList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 140, 460, 220);

        acceptButton.setText("Aceptar");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(acceptButton);
        acceptButton.setBounds(200, 380, 100, 30);

        stationSelectorLabel.setText("Emisora");
        jPanel1.add(stationSelectorLabel);
        stationSelectorLabel.setBounds(340, 70, 53, 17);

        playListNameLabel.setText("Nombre");
        jPanel1.add(playListNameLabel);
        playListNameLabel.setBounds(130, 70, 60, 17);

        importSoundOption.setText("Importar");
        baseFrameMenuBar.add(importSoundOption);

        closeAppOption.setText("Salir");
        baseFrameMenuBar.add(closeAppOption);

        setJMenuBar(baseFrameMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playListNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playListNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playListNameFieldActionPerformed

    private void stationOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stationOptionsActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JButton acceptButton;
    private javax.swing.JMenuBar baseFrameMenuBar;
    private javax.swing.JMenu closeAppOption;
    private javax.swing.JMenu importSoundOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel playListCreatorTittleLabel;
    private javax.swing.JTextField playListNameField;
    private javax.swing.JLabel playListNameLabel;
    private javax.swing.JTable soundsList;
    private javax.swing.JComboBox<String> stationOptions;
    private javax.swing.JLabel stationSelectorLabel;
    // End of variables declaration//GEN-END:variables
}
